2024-10-31 11:27:45,648 INFO: Attempting to register user: string@ [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:69]
2024-10-31 11:27:45,649 ERROR: Registration failed for user string@: Username or email already registered [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:87]
2024-10-31 11:28:08,173 INFO: Attempting to register user: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:69]
2024-10-31 11:28:09,749 ERROR: Unexpected error during registration for user mola: 'hashed_password' is an invalid keyword argument for User [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:90]
2024-10-31 13:09:15,660 INFO: Attempting to register user: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:69]
2024-10-31 13:09:16,096 ERROR: Unexpected error during registration for user mola: 'hashed_password' is an invalid keyword argument for User [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:90]
2024-10-31 13:13:10,776 INFO: Attempting to register user: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:69]
2024-10-31 13:13:11,338 INFO: User registered successfully: mola [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:84]
2024-10-31 13:13:56,393 INFO: User mola@mola.co.ke logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-10-31 14:04:59,495 INFO: User mola@mola.co.ke logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-10-31 14:08:33,120 INFO: User mola@mola.co.ke logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-10-31 14:08:57,320 INFO: User mola@mola.co.ke logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-10-31 17:01:49,770 INFO: User mola@mola.co.ke logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-10-31 17:45:35,868 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:16:54,752 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:27:06,108 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:37:45,977 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:39:40,409 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:43:16,647 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 13:53:03,598 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 14:06:57,798 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 14:14:24,271 INFO: Attempting to register user: string@books [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:69]
2024-11-02 14:14:24,734 INFO: User registered successfully: string@books [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:84]
2024-11-02 14:26:46,072 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 15:38:08,349 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 16:08:50,826 INFO: User molasboy@example.com logged in successfully. [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:63]
2024-11-02 16:14:08,695 INFO: User logout attempt [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:100]
2024-11-02 16:14:08,702 INFO: Received token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtb2xhc2JveUBleGFtcGxlLmNvbSIsImV4cCI6MTczMDU1NDczMH0.07PI-BCs4hYUGMXcjND9qYBi99bv4LwJrrEpyOdafEQ [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:101]
2024-11-02 16:14:08,706 INFO: User successfully logged out [in C:\Users\skmola.TELKOM\Desktop\projects\python\appapi\mapsapi\app\Auth\auth.py:105]
